name: dina-cake-frontend-project # <--- Уникальное имя!

services:
    web:
        build: .
        container_name: dina-cake_frontend
        restart: always
        ports:
            # Слева порт хоста (4002), Справа порт внутри (80)
            - "127.0.0.1:4005:80"
